server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: chatgpt-api-microservice
          uri: http://localhost:8081/
          predicates:
            - Path=/chatgpt-api/**
#        - id: second-microservice
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/second/**