server:
  port: 8080

eureka:
#  instance:
#    hostname: gateway-api
#    prefer-ip-address: true
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://serviceregistry:8761/eureka/
spring:
#  main:
#    web-application-type: reactive
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: chatgpt-api-microservice
#          uri: http://localhost:8081/
          uri: lb://chatgpt-api-microservice
          predicates:
            - Path=/api/**
#        - id: second-microservice
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/second/**