version: '3.7'
services:
  serviceregistry:
#    container_name: 'serviceregistry'
#    hostname: 'serviceregistry'
    build: eureka-server/
    ports:
      - "8761:8761"
#    expose:
#      - "8761"
    networks:
      - backend

  gateway-api:
#    container_name: 'gateway-api'
#    hostname: 'gateway-api'
    build: gateway-api/
    ports:
      - "8080:8080"
#    expose:
#      - "8080"
    environment:
      - eureka.client.service-url.defaultZone=http://serviceregistry:8761/eureka
    networks:
      - backend
#    links:
#      - eureka-server
    depends_on:
      - serviceregistry

  chatgpt-api-microservice:
#    container_name: 'chatgpt-api-microservice'
#    hostname: 'chatgpt-api-microservice'
    build: chatgpt-api-microservice/
    ports:
      - "8081:8081"
    environment:
      - eureka.client.service-url.defaultZone=http://serviceregistry:8761/eureka
#    expose:
#      - "8001"
    networks:
      - backend
#    links:
#      - eureka-server
    depends_on:
      - serviceregistry

  # ---------------------------
  # Service Two Database
  # ---------------------------
  service-two-db:
#    container_name: "service-two-db"
#    hostname: "servicetwodb"
    image: "mysql/mysql-server:latest"
    platform: linux/arm64/v8
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=service-two
      - MYSQL_USER=service-two
      - MYSQL_PASSWORD=service-two
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - backend

  # ---------------------------
  # Service Two
  # ---------------------------
  service-two:
    build: service-two/
    ports:
      - "8082:8082"
    environment:
      - eureka.client.service-url.defaultZone=http://serviceregistry:8761/eureka
    networks:
      - backend
    depends_on:
      - serviceregistry
      - service-two-db

networks:
  backend:
    driver: bridge