version: '3.7'
services:
  serviceregistry:
#    container_name: 'serviceregistry'
#    hostname: 'serviceregistry'
    build: eureka-server/
    ports:
      - "8761:8761"
#    expose:
#      - "8761"
    networks:
      - backend

  gateway-api:
#    container_name: 'gateway-api'
#    hostname: 'gateway-api'
    build: gateway-api/
    ports:
      - "8080:8080"
#    expose:
#      - "8080"
    environment:
      - eureka.client.service-url.defaultZone=http://serviceregistry:8761/eureka
    networks:
      - backend
#    links:
#      - eureka-server
    depends_on:
      - serviceregistry

  chatgpt-api-microservice:
#    container_name: 'chatgpt-api-microservice'
#    hostname: 'chatgpt-api-microservice'
    build: chatgpt-api-microservice/
    ports:
      - "8001:8001"
    environment:
      - eureka.client.service-url.defaultZone=http://serviceregistry:8761/eureka
#    expose:
#      - "8001"
    networks:
      - backend
#    links:
#      - eureka-server
    depends_on:
      - serviceregistry

networks:
  backend:
    driver: bridge