spring:
  application:
    name: chatgpt-api-microservice
server:
  port: 8081

  eureka:
#    instance:
#      hostname: chat-gpt-api-microservice
#    prefer-ip-address: true
    client:
      serviceUrl:
        register-with-eureka: true #確保會註冊
        fetch-registry: true #確保會註冊
        defaultZone: http://serviceregistry:8761/eureka/ #對照eureka server路徑