server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: ${eureka_url:http://localhost:8761/eureka}
#      defaultZone: http://eureka-server:8761/eureka
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
#  instance:
#    hostname: eureka-server
#    hostname: "${HOSTNAME:localhost}.eureka"
#    prefer-ip-address: true